-- OPPORTA Phase 4B: additive discovery review fields and approved-source store.
-- Safe to rerun. Both tables remain private under row-level security.

CREATE TABLE IF NOT EXISTS public.approved_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id text NOT NULL UNIQUE,
    url text NOT NULL UNIQUE,
    title text,
    domain text,
    state text,
    district text,
    source_type text,
    category text DEFAULT 'unknown',
    confidence_score integer DEFAULT 0,
    approved_by text,
    approved_at timestamptz,
    status text DEFAULT 'active',
    requires_ocr boolean DEFAULT false,
    requires_playwright boolean DEFAULT false,
    requires_captcha boolean DEFAULT false,
    notes text
);

ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending_review';
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS reviewed_by text;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS reviewed_at timestamptz;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS review_note text;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS approved_at timestamptz;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS approved_source_id text;

ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS source_id text;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS url text;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS district text;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS source_type text;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS category text DEFAULT 'unknown';
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS confidence_score integer DEFAULT 0;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS approved_by text;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS approved_at timestamptz;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS requires_ocr boolean DEFAULT false;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS requires_playwright boolean DEFAULT false;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS requires_captcha boolean DEFAULT false;
ALTER TABLE IF EXISTS public.approved_sources
    ADD COLUMN IF NOT EXISTS notes text;

ALTER TABLE IF EXISTS public.approved_sources ENABLE ROW LEVEL SECURITY;
