-- OPPORTA Phase 4B: additive review queue for files found on approved sources.
-- Safe to rerun. Scanner findings are private and never become public records.

CREATE TABLE IF NOT EXISTS public.discovered_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_url text NOT NULL UNIQUE,
    source_url text,
    file_name text,
    file_type text,
    title text,
    state text,
    district text,
    category text DEFAULT 'unknown',
    source_id text,
    hash text,
    status text DEFAULT 'pending_review',
    confidence_score integer DEFAULT 0,
    requires_ocr boolean DEFAULT false,
    requires_manual_review boolean DEFAULT true,
    discovered_at timestamptz,
    last_seen_at timestamptz
);

ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS file_url text;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS source_url text;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS file_name text;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS file_type text;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS district text;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS category text DEFAULT 'unknown';
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS source_id text;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS hash text;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending_review';
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS confidence_score integer DEFAULT 0;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS requires_ocr boolean DEFAULT false;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS requires_manual_review boolean DEFAULT true;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS discovered_at timestamptz;
ALTER TABLE IF EXISTS public.discovered_files
    ADD COLUMN IF NOT EXISTS last_seen_at timestamptz;

ALTER TABLE IF EXISTS public.discovered_files ENABLE ROW LEVEL SECURITY;
