-- OPPORTA Phase 4A: additive discovery-review queue.
-- Safe to rerun and intentionally additive. The queue remains unavailable to
-- public/anonymous clients.

CREATE TABLE IF NOT EXISTS public.discovered_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL UNIQUE,
    title text,
    domain text,
    state text,
    district text,
    source_type text,
    category text DEFAULT 'unknown',
    matched_keywords jsonb DEFAULT '[]'::jsonb,
    confidence_score integer DEFAULT 0,
    discovered_from text,
    first_seen_at timestamptz,
    last_seen_at timestamptz,
    robots_allowed boolean DEFAULT true,
    requires_ocr boolean DEFAULT false,
    requires_playwright boolean DEFAULT false,
    requires_captcha boolean DEFAULT false,
    status text DEFAULT 'pending_review',
    reason text
);

ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS url text;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS district text;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS source_type text;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS category text DEFAULT 'unknown';
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS matched_keywords jsonb DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS confidence_score integer DEFAULT 0;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS discovered_from text;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS first_seen_at timestamptz;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS last_seen_at timestamptz;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS robots_allowed boolean DEFAULT true;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS requires_ocr boolean DEFAULT false;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS requires_playwright boolean DEFAULT false;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS requires_captcha boolean DEFAULT false;
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending_review';
ALTER TABLE IF EXISTS public.discovered_sources
    ADD COLUMN IF NOT EXISTS reason text;

ALTER TABLE IF EXISTS public.discovered_sources ENABLE ROW LEVEL SECURITY;
