'use client'

import { useRef, useState } from 'react'
import { Upload, X, FileText, Sparkles, Download, Copy, Building2, ClipboardList } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useToast } from '@/components/ui/toast'
import { cn } from '@/lib/utils'

interface Fields {
  firmName: string
  contractorClass: string
  turnover: string
  experience: string
  tenderTitle: string
  department: string
  nitNumber: string
  estimatedValue: string
  emd: string
  deadline: string
  scope: string
}

const EMPTY: Fields = {
  firmName: '', contractorClass: '', turnover: '', experience: '',
  tenderTitle: '', department: '', nitNumber: '', estimatedValue: '', emd: '', deadline: '', scope: '',
}

function buildDraft(f: Fields, firmDocs: File[], tenderDoc: File | null): string {
  const today = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
  const docList = firmDocs.length
    ? firmDocs.map((d, i) => `   ${i + 1}. ${d.name}`).join('\n')
    : '   (attach: Company PAN, GST certificate, work-experience certificates, audited balance sheets, bank solvency certificate)'
  return `BID SUBMISSION — TECHNICAL & COMMERCIAL PROPOSAL
${'='.repeat(56)}

Date: ${today}

To,
The Tender Inviting Authority
${f.department || '[Department / Organization]'}

Subject: Submission of bid for "${f.tenderTitle || '[Tender Title]'}"
${f.nitNumber ? `NIT / Tender No.: ${f.nitNumber}` : ''}

Respected Sir/Madam,

1. INTRODUCTION
We, ${f.firmName || '[Firm Name]'}, submit our proposal for the above-referenced
tender${f.estimatedValue ? ` (estimated value ${f.estimatedValue})` : ''}. We confirm that we have
studied the tender document, terms & conditions, scope of work, and specifications
in full and agree to abide by them.

2. FIRM CREDENTIALS
   • Firm / Company: ${f.firmName || '[Firm Name]'}
   • Contractor class / registration: ${f.contractorClass || '[Class]'}
   • Average annual turnover: ${f.turnover ? `₹ ${f.turnover} lakhs` : '[Turnover]'}
   • Relevant experience: ${f.experience ? `${f.experience} years` : '[Experience]'}

3. UNDERSTANDING OF SCOPE
${f.scope || '[Summarize your understanding of the scope of work and methodology here.]'}

4. ELIGIBILITY & EMD
   • We meet the eligibility criteria specified in the tender.
   ${f.emd ? `• Earnest Money Deposit (EMD): ${f.emd}, furnished as required.` : '• EMD furnished as per tender requirement.'}
   ${f.deadline ? `• Submitted on or before the deadline: ${f.deadline}.` : ''}

5. DOCUMENTS ENCLOSED
${docList}
${tenderDoc ? `\n   Reference tender document: ${tenderDoc.name}` : ''}

6. DECLARATION
We hereby declare that the information furnished above is true and correct to the
best of our knowledge, and that we have not been blacklisted by any government
department or agency.

Yours faithfully,

For ${f.firmName || '[Firm Name]'}

(Authorized Signatory)
Name:
Designation:
Seal & Date:

${'-'.repeat(56)}
Draft generated by OPPORTA — review and edit before official submission.
`
}

export function BidDrafter() {
  const { toast } = useToast()
  const [f, setF] = useState<Fields>(EMPTY)
  const [firmDocs, setFirmDocs] = useState<File[]>([])
  const [tenderDoc, setTenderDoc] = useState<File | null>(null)
  const [draft, setDraft] = useState<string | null>(null)
  const firmInput = useRef<HTMLInputElement>(null)
  const tenderInput = useRef<HTMLInputElement>(null)

  const set = <K extends keyof Fields>(k: K, v: string) => setF((p) => ({ ...p, [k]: v }))

  const addFirmDocs = (list: FileList | null) => {
    if (!list) return
    setFirmDocs((prev) => [...prev, ...Array.from(list)])
  }

  const generate = () => {
    if (!f.tenderTitle && !tenderDoc) {
      toast('Add tender details', 'info', { description: 'Enter a tender title or upload the tender document first.' })
      return
    }
    setDraft(buildDraft(f, firmDocs, tenderDoc))
    toast('Draft generated', 'success', { description: 'Review and edit it below, then download.' })
  }

  const download = () => {
    if (!draft) return
    const blob = new Blob([draft], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `bid-draft-${(f.nitNumber || f.tenderTitle || 'tender').replace(/[^a-z0-9]+/gi, '-').slice(0, 40)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const copy = async () => {
    if (!draft) return
    await navigator.clipboard.writeText(draft)
    toast('Copied to clipboard', 'success')
  }

  const inputCls =
    'w-full rounded-lg border border-border-subtle bg-surface-elevated px-3 py-2.5 text-sm text-text-primary placeholder:text-text-muted focus:border-brand-blue focus:outline-none transition-colors'

  return (
    <div className="rounded-2xl card-premium p-6 mb-8">
      <div className="flex items-center gap-2 mb-1">
        <Sparkles className="w-4 h-4 text-brand-blue" />
        <h2 className="font-heading font-semibold text-base text-text-primary">Draft a Bid for Any Tender</h2>
      </div>
      <p className="text-xs text-text-muted mb-5">
        Upload your firm documents and the tender file (or just type the details) to generate a ready-to-edit draft bid — works for any tender, even ones outside OPPORTA.
      </p>

      <div className="grid md:grid-cols-2 gap-5">
        {/* Firm details */}
        <div className="space-y-3">
          <p className="text-xs font-semibold uppercase tracking-wide text-text-muted flex items-center gap-1.5"><Building2 className="w-3.5 h-3.5" /> Your firm</p>
          <input className={inputCls} placeholder="Firm / company name" value={f.firmName} onChange={(e) => set('firmName', e.target.value)} />
          <div className="grid grid-cols-2 gap-3">
            <input className={inputCls} placeholder="Contractor class" value={f.contractorClass} onChange={(e) => set('contractorClass', e.target.value)} />
            <input className={inputCls} placeholder="Turnover (₹ lakhs)" value={f.turnover} onChange={(e) => set('turnover', e.target.value)} />
          </div>
          <input className={inputCls} placeholder="Experience (years)" value={f.experience} onChange={(e) => set('experience', e.target.value)} />

          <input ref={firmInput} type="file" multiple className="hidden" onChange={(e) => addFirmDocs(e.target.files)} />
          <button onClick={() => firmInput.current?.click()}
            className="w-full flex items-center justify-center gap-2 rounded-lg border border-dashed border-border-subtle bg-surface-elevated/50 px-3 py-3 text-xs font-medium text-text-secondary hover:text-text-primary hover:border-brand-blue/40 transition-colors">
            <Upload className="w-3.5 h-3.5" /> Upload firm documents (PAN, GST, certificates…)
          </button>
          {firmDocs.length > 0 && (
            <ul className="space-y-1.5">
              {firmDocs.map((d, i) => (
                <li key={i} className="flex items-center justify-between gap-2 rounded-md bg-surface-elevated px-2.5 py-1.5 text-xs text-text-secondary">
                  <span className="flex items-center gap-1.5 truncate"><FileText className="w-3 h-3 flex-shrink-0" />{d.name}</span>
                  <button onClick={() => setFirmDocs((prev) => prev.filter((_, x) => x !== i))} aria-label="Remove">
                    <X className="w-3 h-3 text-text-muted hover:text-danger" />
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* Tender details */}
        <div className="space-y-3">
          <p className="text-xs font-semibold uppercase tracking-wide text-text-muted flex items-center gap-1.5"><ClipboardList className="w-3.5 h-3.5" /> The tender</p>
          <input className={inputCls} placeholder="Tender title" value={f.tenderTitle} onChange={(e) => set('tenderTitle', e.target.value)} />
          <input className={inputCls} placeholder="Department / organization" value={f.department} onChange={(e) => set('department', e.target.value)} />
          <div className="grid grid-cols-2 gap-3">
            <input className={inputCls} placeholder="NIT / Tender no." value={f.nitNumber} onChange={(e) => set('nitNumber', e.target.value)} />
            <input className={inputCls} placeholder="Estimated value" value={f.estimatedValue} onChange={(e) => set('estimatedValue', e.target.value)} />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <input className={inputCls} placeholder="EMD" value={f.emd} onChange={(e) => set('emd', e.target.value)} />
            <input className={inputCls} placeholder="Deadline" value={f.deadline} onChange={(e) => set('deadline', e.target.value)} />
          </div>

          <input ref={tenderInput} type="file" className="hidden" onChange={(e) => setTenderDoc(e.target.files?.[0] ?? null)} />
          <button onClick={() => tenderInput.current?.click()}
            className="w-full flex items-center justify-center gap-2 rounded-lg border border-dashed border-border-subtle bg-surface-elevated/50 px-3 py-3 text-xs font-medium text-text-secondary hover:text-text-primary hover:border-brand-blue/40 transition-colors">
            <Upload className="w-3.5 h-3.5" /> Upload tender document (PDF / NIT)
          </button>
          {tenderDoc && (
            <div className="flex items-center justify-between gap-2 rounded-md bg-surface-elevated px-2.5 py-1.5 text-xs text-text-secondary">
              <span className="flex items-center gap-1.5 truncate"><FileText className="w-3 h-3 flex-shrink-0" />{tenderDoc.name}</span>
              <button onClick={() => setTenderDoc(null)} aria-label="Remove"><X className="w-3 h-3 text-text-muted hover:text-danger" /></button>
            </div>
          )}
        </div>
      </div>

      <div className="mt-4">
        <textarea className={cn(inputCls, 'min-h-20 resize-y')} placeholder="Scope / methodology summary (optional)" value={f.scope} onChange={(e) => set('scope', e.target.value)} />
      </div>

      <div className="mt-5 flex flex-wrap gap-2">
        <Button size="sm" onClick={generate} className="btn-glow bg-brand-blue hover:bg-brand-blue/90 text-white font-semibold gap-1.5">
          <Sparkles className="w-3.5 h-3.5" /> Generate Draft Bid
        </Button>
        {draft && (
          <>
            <Button size="sm" variant="outline" onClick={download} className="border-border-subtle text-text-secondary hover:bg-surface-elevated gap-1.5">
              <Download className="w-3.5 h-3.5" /> Download (.txt)
            </Button>
            <Button size="sm" variant="outline" onClick={copy} className="border-border-subtle text-text-secondary hover:bg-surface-elevated gap-1.5">
              <Copy className="w-3.5 h-3.5" /> Copy
            </Button>
          </>
        )}
      </div>

      {draft && (
        <textarea
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          className="mt-4 w-full min-h-80 rounded-xl border border-border-subtle bg-background/60 px-4 py-3 font-mono text-xs leading-relaxed text-text-secondary focus:border-brand-blue focus:outline-none"
        />
      )}
    </div>
  )
}
